Repository SuperDARN/pydarn, pull requests merged in 2021-03, with the labels that each got.

#112 [EHN] Multi Grid plotting
  pydarn/plotting/grid.py
Labels: enhancement

#113 fixed the warning message on fan plots
  pydarn/__init__.py
  pydarn/plotting/fan.py
Labels: bug

#127 FIX/Offset between major and minor ticks using slant range in RTPs
  pydarn/plotting/rtp.py
Labels: bug

#123 Docs/dev workflow
  docs/dev/branching.md
  docs/dev/copyright_license.md
  docs/dev/issues.md
  docs/dev/projects.md
  docs/index.md
  mkdocs.yml
Labels: Documentation

#135 [EHN] Coordinate Enumerator for future coordinate systems
  .github/pull_request_template.md
  .github/workflows/flake8PR.yml
  pydarn/__init__.py
  pydarn/exceptions/warning_formatting.py
  pydarn/plotting/rtp.py
  pydarn/utils/coordinates.py
Labels: easy PR, enhancement

#131 [FIX] updating citing link in warning
  pydarn/__init__.py
  pydarn/exceptions/warning_formatting.py
  pydarn/plotting/acf.py
  pydarn/plotting/fan.py
  pydarn/plotting/power.py
  pydarn/plotting/rtp.py
Labels: bug, easy PR, enhancement

#140 Fix for dropped beam in plot_fan and plot_fov
  pydarn/plotting/fan.py
Labels: bug, easy PR

#125 [Docs] pyDARN Release Guidelines
  docs/dev/releases.md
  docs/index.md
  mkdocs.yml
Labels: Documentation, enhancement

#110 Doc/communication guidelines
  docs/dev/communication.md
  docs/index.md
  mkdocs.yml
Labels: DAWG chair Input, Documentation
