Repository SuperDARN/pydarn, pull requests merged in 2021-04, with the labels that each got.

#134 [FIX] Plot RTPs from edge of range gate not center value
  pydarn/plotting/rtp.py
Labels: Scientist help, bug, telecon

#115 fixed slant range centre bug
  pydarn/utils/conversions.py
Labels: Scientist help, bug

#148 FIX: Get rxrise from hdw
  pydarn/plotting/rtp.py
  pydarn/utils/conversions.py
Labels: Documentation, bug, discussion

#108 Add code of conduct 1
  CODE_OF_CONDUCT.md
  README.md
  docs/dev/communication.md
  docs/dev/team.md
  docs/index.md
  mkdocs.yml
Labels: DAWG chair Input, Documentation, enhancement

#152 added costants file
  pydarn/__init__.py
  pydarn/utils/constants.py
  pydarn/utils/conversions.py
Labels: easy PR, enhancement
