Repository SuperDARN/pydarn, pull requests merged in 2021-05, with the labels that each got.

#155 Ehn/datetime scanindex
  pydarn/plotting/fan.py
Labels: easy PR

#154 [EHN] Coordinates
  pydarn/__init__.py
  pydarn/plotting/rtp.py
  pydarn/utils/coordinates.py
  pydarn/utils/radar_pos.py
Labels: easy PR

#159 EHN: Hemisphere determination in Fan plots
  pydarn/plotting/fan.py
Labels: easy PR

#156 added title functionality
  pydarn/plotting/fan.py
Labels: easy PR

#161 FIX: Function radar_fov call in plot_fov needed updating to use the new Coords.AACGM
  pydarn/plotting/fan.py
Labels: bug, easy PR

#158 EHN: Fan pcolormesh
  pydarn/plotting/fan.py
Labels: Scientist help, enhancement

#151 Ehn/rtp ground scatter range
  pydarn/__init__.py
  pydarn/plotting/rtp.py
  pydarn/utils/conversions.py
  pydarn/utils/coordinates.py
Labels: enhancement

#162 EHN: Radar Position Dots and Labels
  pydarn/plotting/fan.py
Labels: enhancement, question, workaround

#106 [EHN] plot Grid
  pydarn/__init__.py
  pydarn/exceptions/plot_exceptions.py
  pydarn/plotting/acf.py
  pydarn/plotting/fan.py
  pydarn/plotting/grid.py
  pydarn/plotting/rtp.py
  pydarn/utils/superdarn_radars.py
Labels: enhancement

#138 Doc/grid plot
  docs/imgs/grid_1.png
  docs/imgs/grid_2.png
  docs/index.md
  docs/user/grid.md
  mkdocs.yml
Labels: Documentation, easy PR

#165 Fix/scan index
  pydarn/plotting/fan.py
Labels: FIX, easy PR

#164 Updating Docs for 2.1 Release
  docs/dev/communication.md
  docs/dev/issues.md
  docs/dev/projects.md
  docs/dev/releases.md
  docs/imgs/fan_1.b.png
  docs/imgs/fan_1.png
  docs/imgs/fan_2.png
  docs/imgs/fan_3.png
  docs/imgs/fov_1.png
  docs/imgs/fov_2.png
  docs/imgs/fov_3.png
  docs/imgs/fov_4.png
  docs/imgs/rtp_1.png
  docs/imgs/summary_1.png
  docs/index.md
  docs/user/axis.md
  docs/user/coordinates.md
  docs/user/fan.md
  docs/user/fov.md
  docs/user/install.md
  docs/user/range_time.md
  docs/user/summary.md
  mkdocs.yml
  pydarn/plotting/axis.py
  pydarn/plotting/fan.py
  pydarn/utils/conversions.py
  pydarn/utils/coordinates.py
Labels: Documentation
