Repository SuperDARN/pydarn, pull requests merged in 2021-09, with the labels that each got.

#186 Pytest/structure
  .travis.yml
  test/test_Fan.py
  test/test_Grid.py
  test/test_RTP.py
Labels: enhancement, easy PR

#180 Ehn/pytest
  .travis.yml
  pydarn/plotting/rtp.py
  test/data/test.fitacf.bz2
  test/data/test.grd
  test/data/test.rawacf.bz2
  test/data/test_south.fitacf.bz2
  test/test_Fan.py
  test/test_Grid.py
  test/test_RTP.py
  test/unit/test_rtp.py
Labels: enhancement

#193 EHN: Grid key word in FOV to plot the grid of gates and beams
  docs/user/fov.md
  pydarn/plotting/fan.py
  test/test_Fan.py
Labels: enhancement, easy PR

#194 EHN: Channel keyword for Fan plots
  docs/user/fan.md
  docs/user/range_time.md
  pydarn/__init__.py
  pydarn/exceptions/plot_exceptions.py
  pydarn/exceptions/warning_formatting.py
  pydarn/plotting/fan.py
  test/test_Fan.py
Labels: enhancement, question, FIX

#197 Modularization of virtual heights
  pydarn/utils/radar_pos.py
  pydarn/utils/virtual_heights.py
  pydarn/utils/virtual_heights_types.py
Labels: enhancement, easy PR
