Repository SuperDARN/pydarn, pull requests merged in 2021-11, with the labels that each got.

#210 FIX: Require pydarnio version 1.1.0
  setup.py
Labels: FIX

#208 FIX: Summary plot rendering bug
  pydarn/plotting/rtp.py
Labels: High Priority, FIX

#216 added axes to plot_fov call in plot_fab
  pydarn/plotting/fan.py
Labels: easy PR, FIX

#214 Ehn/citing warning
  pydarn/__init__.py
  pydarn/exceptions/warning_formatting.py
  pydarn/plotting/acf.py
  pydarn/plotting/fan.py
  pydarn/plotting/grid.py
  pydarn/plotting/power.py
  pydarn/plotting/rtp.py
Labels: enhancement, easy PR
