Repository SuperDARN/pydarn, pull requests merged in 2021-07, with the labels that each got.

#174 [FIX] scan_index bug
  pydarn/plotting/fan.py
Labels: FIX, easy PR

#176 swapped the hemisphere and range gate value for ADW
  pydarn/utils/superdarn_radars.py
Labels: FIX, easy PR

#169 Ehn/add kwargs
  docs/imgs/pwr0_range-time.png
  pydarn/plotting/fan.py
  pydarn/plotting/grid.py
  pydarn/plotting/rtp.py
Labels: enhancement

#178 EHN: RTP Start Time Rounding Options
  pydarn/plotting/rtp.py
Labels: easy PR, enhancement
