Repository SuperDARN/pydarn, pull requests merged in 2022-03, with the labels that each got.

#202 [EHN] convection maps!
  docs/imgs/map_1.png
  docs/imgs/map_2.png
  docs/index.md
  docs/user/map.md
  mkdocs.yml
  pydarn/__init__.py
  pydarn/plotting/grid.py
  pydarn/plotting/maps.py
  pydarn/utils/plotting.py
Labels: enhancement, help wanted

#232 FIX: plot_fan variable return order changes and boundary option redo
  pydarn/plotting/fan.py
  pydarn/plotting/maps.py
Labels: good first issue, easy PR, FIX

#222 FIX: Range option lower limit caused issues with indexing arrays
  pydarn/plotting/fan.py
  pydarn/utils/radar_pos.py
Labels: FIX

#234 FIX: plot_fov fix for Grid plots
  pydarn/plotting/grid.py
  pydarn/utils/conversions.py
Labels: good first issue, easy PR, FIX

#237 Fix/partial grid records
  pydarn/exceptions/plot_exceptions.py
  pydarn/plotting/grid.py
  pydarn/plotting/maps.py
Labels: enhancement, Error/Warning, easy PR, FIX

#247 FIX: Bug where FOV in a fan plot is coloured white
  pydarn/plotting/fan.py
Labels: easy PR, FIX

#245 Ehn/grid lines cartopy
  pydarn/plotting/fan.py
  pydarn/plotting/projections.py
Labels: enhancement, easy PR

#246 Ehn/error aacgm geo
  pydarn/exceptions/plot_exceptions.py
  pydarn/plotting/fan.py
Labels: easy PR, FIX

#241 EHN: Convection Contours and HMB
  pydarn/plotting/maps.py
Labels: enhancement, telecon
