Repository SuperDARN/pydarn, pull requests merged in 2023-05, with the labels that each got.

#315 Fixed function descriptions in projections.py
  pydarn/plotting/projections.py
Labels: easy PR

#309 FIX: Lowlat scatter was not clipped on Maps
  pydarn/plotting/maps.py
Labels: easy PR, FIX

#303 EHN: Options to Plot a Terminator
  docs/user/coordinates.md
  pydarn/__init__.py
  pydarn/exceptions/warning_formatting.py
  pydarn/plotting/projections.py
  pydarn/utils/terminator.py
Labels: enhancement
