Repository SuperDARN/pydarn, pull requests merged in 2024-07, with the labels that each got.

#390 Fix: Embargo open bracket typo
  pydarn/__init__.py
  pydarn/plotting/fan.py
  pydarn/plotting/rtp.py
  pydarn/utils/plotting.py
Labels: High Priority, FIX

#382 REF: Axes handling for projections - new geomagnetic zoomable plotting
  pydarn/plotting/fan.py
  pydarn/plotting/grid.py
  pydarn/plotting/maps.py
  pydarn/plotting/projections.py
Labels: enhancement, refactor

#394 DEP: Matplotlib plot_date deprecation
  pydarn/plotting/rtp.py
Labels: good first issue, High Priority, easy PR

#395 DOCS: Update documentation for v4.1 release
  docs/imgs/acf_plot1.png
  docs/imgs/axis_GEO.png
  docs/imgs/axis_MAG.png
  docs/imgs/axis_POLAR.png
  docs/imgs/fan_user_input.png
  docs/imgs/plot_acf_2.png
  docs/index.md
  docs/user/acf.md
  docs/user/axis.md
  docs/user/citing.md
  docs/user/coord_time.md
  docs/user/coordinates.md
  docs/user/fan.md
  docs/user/fov.md
  docs/user/grid.md
  docs/user/install.md
  docs/user/map.md
  docs/user/superdarn_data.md
  mkdocs.yml
  test/test_Fan.py
Labels: Documentation, easy PR

#388 EHN: Make Cartopy a full dependency
  pydarn/__init__.py
  pydarn/exceptions/plot_exceptions.py
  pydarn/exceptions/warning_formatting.py
  pydarn/plotting/projections.py
  pydarn/utils/geocoastline.py
  setup.cfg
Labels: enhancement

#391 NEW: Map Potential Time Series at Given MLON/MLAT
  pydarn/plotting/maps.py
  pydarn/utils/plotting.py
Labels: enhancement

#400 EHN: Flexibility on Plotting Summary Plot Variables
  pydarn/plotting/rtp.py
Labels: enhancement
